//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Six.Scs.QA.Selenium.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Six.Scs.QA.Selenium.Common.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#applicationBar div#applicationInformation span#ctl00_lblApplicationName.
        /// </summary>
        public static string ApplicationInfo_ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationInfo_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#applicationBar div#applicationInformation span#ctl00_lblEnvironmentText.
        /// </summary>
        public static string ApplicationInfo_Environment {
            get {
                return ResourceManager.GetString("ApplicationInfo_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#footerNavigationBar&gt;div#copyright.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#footerNavigationBar&gt;a[href*=&apos;/disclaimer.aspx&apos;].
        /// </summary>
        public static string Footer_Disclaimer {
            get {
                return ResourceManager.GetString("Footer_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#footerNavigationBar&gt;a#ctl00_hplFeedback.
        /// </summary>
        public static string Footer_Feedback {
            get {
                return ResourceManager.GetString("Footer_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#footerFunctionBar&gt;a[href*=&apos;JavaScript:Page.Print()&apos;].
        /// </summary>
        public static string Footer_PrintPage {
            get {
                return ResourceManager.GetString("Footer_PrintPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#footerFunctionBar&gt;a[href*=&apos;JavaScript:window.scroll(0,0)&apos;].
        /// </summary>
        public static string Footer_ScrollUp {
            get {
                return ResourceManager.GetString("Footer_ScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.formAlert ul li.
        /// </summary>
        public static string FormAlert_FormAlertElements {
            get {
                return ResourceManager.GetString("FormAlert_FormAlertElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html&gt;body&gt;img.companyLogo.
        /// </summary>
        public static string Lobby_CompanyLogo {
            get {
                return ResourceManager.GetString("Lobby_CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#content h1.
        /// </summary>
        public static string Lobby_Headline {
            get {
                return ResourceManager.GetString("Lobby_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container ul.
        /// </summary>
        public static string LobbyNews_NewsElements {
            get {
                return ResourceManager.GetString("LobbyNews_NewsElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container span#ctl00_bodyContentPlaceHolder_lblNewsTitle h2.
        /// </summary>
        public static string LobbyNews_NewsTitle {
            get {
                return ResourceManager.GetString("LobbyNews_NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#metaNavBar a#ctl00_hplLanguages.menu.
        /// </summary>
        public static string MetaNavBar_Languages {
            get {
                return ResourceManager.GetString("MetaNavBar_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#metaNavBar a#ctl00_hplLogout[href*=&apos;/Logout.aspx&apos;].
        /// </summary>
        public static string MetaNavBar_Logout {
            get {
                return ResourceManager.GetString("MetaNavBar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#metaNavBar a#ctl00_hplSimpleUserInfo[href*=&apos;/User/UserEdit.aspx?PageMode=view&amp;UserName=&apos;].
        /// </summary>
        public static string MetaNavBar_User {
            get {
                return ResourceManager.GetString("MetaNavBar_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#tabNavBar div#ctl00_pnlMainMenu div#menuItems a[href*=&apos;AdminOverview&apos;].
        /// </summary>
        public static string NavigationBar_Administration {
            get {
                return ResourceManager.GetString("NavigationBar_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a#ctl00_hplMenuMenuCurrent.
        /// </summary>
        public static string NavigationBar_Current {
            get {
                return ResourceManager.GetString("NavigationBar_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#tabNavBar div#ctl00_pnlMainMenu div#menuItems a[href*=&apos;/Lobby/&apos;].
        /// </summary>
        public static string NavigationBar_Lobby {
            get {
                return ResourceManager.GetString("NavigationBar_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#tabNavBar div#ctl00_pnlMainMenu div#menuItems a#ctl00_hplMenuMore.moreLink.
        /// </summary>
        public static string NavigationBar_MoreMenu {
            get {
                return ResourceManager.GetString("NavigationBar_MoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#tabNavBar .
        /// </summary>
        public static string NavigationBar_Prefix {
            get {
                return ResourceManager.GetString("NavigationBar_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#tabNavBar div#ctl00_pnlMainMenu div#menuItems a[href*=&apos;AnalysisOverview&apos;].
        /// </summary>
        public static string NavigationBar_Reporting {
            get {
                return ResourceManager.GetString("NavigationBar_Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul#TicketList.
        /// </summary>
        public static string ProcessTickets_Container {
            get {
                return ResourceManager.GetString("ProcessTickets_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul#BatchHistoryList.
        /// </summary>
        public static string ProcessTickets_Newest {
            get {
                return ResourceManager.GetString("ProcessTickets_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul#ElementHistoryList.
        /// </summary>
        public static string ProcessTickets_Oldest {
            get {
                return ResourceManager.GetString("ProcessTickets_Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#searchBar&gt;p#searchSubmit.
        /// </summary>
        public static string QuickSearch_SearchButton {
            get {
                return ResourceManager.GetString("QuickSearch_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#searchBar&gt;input#searchText.
        /// </summary>
        public static string QuickSearch_SearchField {
            get {
                return ResourceManager.GetString("QuickSearch_SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container&gt;ul#ElementHistoryList&gt;li&gt;a.
        /// </summary>
        public static string RecentElements_Elements {
            get {
                return ResourceManager.GetString("RecentElements_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container&gt;ul#ElementHistoryList&gt;li:first-child&gt;a.
        /// </summary>
        public static string RecentElements_MostRecent {
            get {
                return ResourceManager.GetString("RecentElements_MostRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a#ctl00_bodyContentPlaceHolder_rptElementHistory_ctl.
        /// </summary>
        public static string RecentElements_RecentElement_Prefix {
            get {
                return ResourceManager.GetString("RecentElements_RecentElement_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _hplElementHistory.
        /// </summary>
        public static string RecentElements_RecentElement_Suffix {
            get {
                return ResourceManager.GetString("RecentElements_RecentElement_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container&gt;ul#BatchHistoryList&gt;li&gt;a.
        /// </summary>
        public static string RecentMassmutations_Elements {
            get {
                return ResourceManager.GetString("RecentMassmutations_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_lblBatchTitle.
        /// </summary>
        public static string RecentMassmutations_Header {
            get {
                return ResourceManager.GetString("RecentMassmutations_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.container a#ctl00_bodyContentPlaceHolder_rptBatchHistory_ctl.
        /// </summary>
        public static string RecentMassmutations_RecentElement_Prefix {
            get {
                return ResourceManager.GetString("RecentMassmutations_RecentElement_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _hplBatchHistory.
        /// </summary>
        public static string RecentMassmutations_RecentElement_Suffix {
            get {
                return ResourceManager.GetString("RecentMassmutations_RecentElement_Suffix", resourceCulture);
            }
        }
    }
}
