//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Extension.TestObjects.Terminal.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Extension.TestObjects.Terminal.Dashboard.DashboardRes", typeof(DashboardRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Customer_Address.
        /// </summary>
        public static string CustomerInfo_Adress {
            get {
                return ResourceManager.GetString("CustomerInfo_Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Customer_Id.
        /// </summary>
        public static string CustomerInfo_Id {
            get {
                return ResourceManager.GetString("CustomerInfo_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Customer_Info.
        /// </summary>
        public static string CustomerInfo_Info {
            get {
                return ResourceManager.GetString("CustomerInfo_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Customer_Name.
        /// </summary>
        public static string CustomerInfo_Name {
            get {
                return ResourceManager.GetString("CustomerInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Location_Address.
        /// </summary>
        public static string LocationInfo_Adress {
            get {
                return ResourceManager.GetString("LocationInfo_Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Location_Id.
        /// </summary>
        public static string LocationInfo_Ep2Id {
            get {
                return ResourceManager.GetString("LocationInfo_Ep2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Location_Name.
        /// </summary>
        public static string LocationInfo_Name {
            get {
                return ResourceManager.GetString("LocationInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Trm_ArticleDisplayName.
        /// </summary>
        public static string TerminalInfo_Article {
            get {
                return ResourceManager.GetString("TerminalInfo_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Trm_ExtId.
        /// </summary>
        public static string TerminalInfo_ExternTerminalId {
            get {
                return ResourceManager.GetString("TerminalInfo_ExternTerminalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Trm_State.
        /// </summary>
        public static string TerminalInfo_Status {
            get {
                return ResourceManager.GetString("TerminalInfo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#DashboardSummaryContainer #TD_Trm_TID.
        /// </summary>
        public static string TerminalInfo_TerminalId {
            get {
                return ResourceManager.GetString("TerminalInfo_TerminalId", resourceCulture);
            }
        }
    }
}
