//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Extension.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DriverRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Extension.Properties.DriverRes", typeof(DriverRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEV.
        /// </summary>
        internal static string DEV {
            get {
                return ResourceManager.GetString("DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleWithCertificate.
        /// </summary>
        internal static string FirefoxProfile_Certificate {
            get {
                return ResourceManager.GetString("FirefoxProfile_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleWithOutCertificate.
        /// </summary>
        internal static string FirefoxProfile_Plain {
            get {
                return ResourceManager.GetString("FirefoxProfile_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetExplorer.
        /// </summary>
        internal static string InternetExplorer {
            get {
                return ResourceManager.GetString("InternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAK.
        /// </summary>
        internal static string QAK {
            get {
                return ResourceManager.GetString("QAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAL.
        /// </summary>
        internal static string QAL {
            get {
                return ResourceManager.GetString("QAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAC.
        /// </summary>
        internal static string UAC {
            get {
                return ResourceManager.GetString("UAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WES_Certificate.
        /// </summary>
        internal static string WES_Certificate {
            get {
                return ResourceManager.GetString("WES_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WES_SecurId.
        /// </summary>
        internal static string WES_SecurId {
            get {
                return ResourceManager.GetString("WES_SecurId", resourceCulture);
            }
        }
    }
}
