//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Six.QA.Selenium.Extension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Six.QA.Selenium.Extension.Properties.ScsRes", typeof(ScsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleWithCertificate.
        /// </summary>
        public static string FirefoxProfile_Certificate {
            get {
                return ResourceManager.GetString("FirefoxProfile_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleWithOutCertificate.
        /// </summary>
        public static string FirefoxProfile_Plain {
            get {
                return ResourceManager.GetString("FirefoxProfile_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcpos.
        /// </summary>
        public static string mandant_prod {
            get {
                return ResourceManager.GetString("mandant_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcposk.
        /// </summary>
        public static string mandant_qa_K {
            get {
                return ResourceManager.GetString("mandant_qa_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcposl.
        /// </summary>
        public static string mandant_qa_L {
            get {
                return ResourceManager.GetString("mandant_qa_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mdzhwcweb01/scs2/.
        /// </summary>
        public static string UAC_DEV {
            get {
                return ResourceManager.GetString("UAC_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wksiegmund01/scs2/.
        /// </summary>
        public static string UAC_LOCAL {
            get {
                return ResourceManager.GetString("UAC_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six_scs_auto_PW.
        /// </summary>
        public static string uac_passwort {
            get {
                return ResourceManager.GetString("uac_passwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six_scs_auto.
        /// </summary>
        public static string uac_username {
            get {
                return ResourceManager.GetString("uac_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gate.telekurs.ch/scs2s/.
        /// </summary>
        public static string WES_Production {
            get {
                return ResourceManager.GetString("WES_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateint.telekurs.ch/scs2c-qa-k/.
        /// </summary>
        public static string WES_QA_K {
            get {
                return ResourceManager.GetString("WES_QA_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateint.telekurs.ch/scs2c-qa-l/.
        /// </summary>
        public static string WES_QA_L {
            get {
                return ResourceManager.GetString("WES_QA_L", resourceCulture);
            }
        }
    }
}
