//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Extension.TestObjects.Customer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerEditRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerEditRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Extension.TestObjects.Customer.CustomerEditRes", typeof(CustomerEditRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_addressAdditionTextBox.
        /// </summary>
        public static string AdressAddition {
            get {
                return ResourceManager.GetString("AdressAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_rowAgency_sugAgency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_rowCashIntegrator_sugCashIntegrator.
        /// </summary>
        public static string CashIntegrator {
            get {
                return ResourceManager.GetString("CashIntegrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_rowCategoryCode_sugDropDowntbx.
        /// </summary>
        public static string CategoryCode {
            get {
                return ResourceManager.GetString("CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_rowCategoryCode_sugDropDown.
        /// </summary>
        public static string CategoryCodeView {
            get {
                return ResourceManager.GetString("CategoryCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_cityTextBox.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_inpCompanyName.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_sugCountrytbx.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_sugCountry.
        /// </summary>
        public static string CountryView {
            get {
                return ResourceManager.GetString("CountryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#CustomerData_CustomerName.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_customerNumberInput.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_emailTextBox.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#ctl00_bodyContentPlaceHolder_rowEP2MerchantID_ep2numberTextBox.
        /// </summary>
        public static string Ep2MerchantId {
            get {
                return ResourceManager.GetString("Ep2MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_faxTextBox.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #LocationData_LocationGUID.
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_sugLanguagetbx.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_sugLanguage.
        /// </summary>
        public static string LanguageView {
            get {
                return ResourceManager.GetString("LanguageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_telephone2TextBox.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_poTextBox.
        /// </summary>
        public static string Po {
            get {
                return ResourceManager.GetString("Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_regionTextBox.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_sapNumberInput.
        /// </summary>
        public static string SapNumber {
            get {
                return ResourceManager.GetString("SapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [id*=&apos;_customerSbsBillingTenant&apos;].
        /// </summary>
        public static string SbsBillingTenant {
            get {
                return ResourceManager.GetString("SbsBillingTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_customerSbsCurrency.
        /// </summary>
        public static string SbsCurrency {
            get {
                return ResourceManager.GetString("SbsCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select#ctl00_bodyContentPlaceHolder_customerSegment.
        /// </summary>
        public static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span#ctl00_bodyContentPlaceHolder_rowCustomerSegment.
        /// </summary>
        public static string SegmentView {
            get {
                return ResourceManager.GetString("SegmentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_streetNameTextBox.
        /// </summary>
        public static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_supplierDropDown_dnSupplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_rowSupportContract_ddSupportContract.
        /// </summary>
        public static string SupportContract {
            get {
                return ResourceManager.GetString("SupportContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_telephoneTextBox.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_webTextBox.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_webLink.
        /// </summary>
        public static string WebView {
            get {
                return ResourceManager.GetString("WebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_bodyContentPlaceHolder_addressControl_zipTextBox.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
