//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Tests.SCSPlatin.TestObjects.Common.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Tests.SCSPlatin.TestObjects.Common.Menu.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassAcqExchange&apos;].
        /// </summary>
        internal static string AcquirerChange {
            get {
                return ResourceManager.GetString("AcquirerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Pages/Person/PersonEdit.aspx?PageMode=view&amp;PERSONID=&apos;].
        /// </summary>
        internal static string ContactMenu_Contact {
            get {
                return ResourceManager.GetString("ContactMenu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Pages/Person/PersonEdit.aspx?PageMode=edit&amp;PERSONID=&apos;].
        /// </summary>
        internal static string ContactMenu_ContactEdit {
            get {
                return ResourceManager.GetString("ContactMenu_ContactEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Mpd/list?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_AllMpds {
            get {
                return ResourceManager.GetString("CustomerMenu_AllMpds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Terminal/TerminalList.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_AllTerminals {
            get {
                return ResourceManager.GetString("CustomerMenu_AllTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/BillingAddress/Edit?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_BillingAddressEdit {
            get {
                return ResourceManager.GetString("CustomerMenu_BillingAddressEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;BillingAddress/New?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_BillingAdressCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_BillingAdressCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;BillingAddress/List?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_BillingAdresses {
            get {
                return ResourceManager.GetString("CustomerMenu_BillingAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Person/CustomerPersonNew?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_ContactCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_ContactCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Person/CustomerPersonList?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_Contacts {
            get {
                return ResourceManager.GetString("CustomerMenu_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Customer/CustomerEdit.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_Customer {
            get {
                return ResourceManager.GetString("CustomerMenu_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Customer/CustomerEdit.aspx?PageMode=new&apos;].
        /// </summary>
        internal static string CustomerMenu_CustomerCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_CustomerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Customer/CustomerDeactivate.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_CustomerDeactivate {
            get {
                return ResourceManager.GetString("CustomerMenu_CustomerDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Customer/CustomerEdit.aspx?PageMode=edit&amp;CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_CustomerEdit {
            get {
                return ResourceManager.GetString("CustomerMenu_CustomerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/CustomerInfoText/Create?&amp;CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_InfotextCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_InfotextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Location/New?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_LocationCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_LocationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Location/LocationList.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_LocationsOfCustomer {
            get {
                return ResourceManager.GetString("CustomerMenu_LocationsOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalNew.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_TerminalCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_TerminalCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Terminal/TerminalList.aspx?CUSTOMERLOCATIONID=&apos;].
        /// </summary>
        internal static string CustomerMenu_TerminalsOfCustomerLocation {
            get {
                return ResourceManager.GetString("CustomerMenu_TerminalsOfCustomerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;TicketList.asp?ListType=customer&amp;CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_Tickets {
            get {
                return ResourceManager.GetString("CustomerMenu_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/LoginNew.asp?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_UserCreate {
            get {
                return ResourceManager.GetString("CustomerMenu_UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;User/UserList.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string CustomerMenu_Users {
            get {
                return ResourceManager.GetString("CustomerMenu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Lobby/&apos;].
        /// </summary>
        internal static string LobbyMenu_Lobby {
            get {
                return ResourceManager.GetString("LobbyMenu_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Person/PersonEdit.aspx?PageMode=new&amp;LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_ContactCreate {
            get {
                return ResourceManager.GetString("LocationMenu_ContactCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Person/PersonList.aspx?CUSTOMERID=&apos;][href*=&apos;&amp;LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_Contacts {
            get {
                return ResourceManager.GetString("LocationMenu_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Pages/InfoText/LocationInfoTextNew.aspx?CUSTOMERID=&apos;].
        /// </summary>
        internal static string LocationMenu_InfotextCreate {
            get {
                return ResourceManager.GetString("LocationMenu_InfotextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;InfoText/LocationInfoTextList.aspx?LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_Infotexts {
            get {
                return ResourceManager.GetString("LocationMenu_Infotexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Location/?LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_Location {
            get {
                return ResourceManager.GetString("LocationMenu_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Location/Edit?LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_LocationEdit {
            get {
                return ResourceManager.GetString("LocationMenu_LocationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Location.asp?mode=Cancel&amp;LocationFunction=&apos;].
        /// </summary>
        internal static string LocationMenu_LocationQuit {
            get {
                return ResourceManager.GetString("LocationMenu_LocationQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Terminal/TerminalNew.aspx?LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_TerminalCreate {
            get {
                return ResourceManager.GetString("LocationMenu_TerminalCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;Terminal/TerminalList.aspx?LOCATIONID=&apos;].
        /// </summary>
        internal static string LocationMenu_Terminals {
            get {
                return ResourceManager.GetString("LocationMenu_Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassMutation/BTMigrationFileUpload.aspx&apos;].
        /// </summary>
        internal static string MassMutationMenu_BusinessTemplateMigrate {
            get {
                return ResourceManager.GetString("MassMutationMenu_BusinessTemplateMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassMutation/ContractsFileUpload.aspx&apos;].
        /// </summary>
        internal static string MassMutationMenu_ContractCreate {
            get {
                return ResourceManager.GetString("MassMutationMenu_ContractCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassMutation/CustomersFileUpload.aspx&apos;].
        /// </summary>
        internal static string MassMutationMenu_CustomerCreate {
            get {
                return ResourceManager.GetString("MassMutationMenu_CustomerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassMutation/LocationsFileUpload.aspx&apos;].
        /// </summary>
        internal static string MassMutationMenu_LocationCreate {
            get {
                return ResourceManager.GetString("MassMutationMenu_LocationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/MassMutation/TerminalsFileUpload.aspx&apos;].
        /// </summary>
        internal static string MassMutationMenu_TerminalCreate {
            get {
                return ResourceManager.GetString("MassMutationMenu_TerminalCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/SIMCard&apos;].
        /// </summary>
        internal static string SimCardManagement {
            get {
                return ResourceManager.GetString("SimCardManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TerminalEP2Log.asp?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_Ep2TraceLog {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_Ep2TraceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/FoMessage/Index?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_FoMessages {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_FoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/FOQueries.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_FoQueries {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_FoQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/GKLP/GKLPBlock.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_GklpBlock {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_GklpBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/ResetNetAddr.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_ResetComAdresses {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_ResetComAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Admin/MessageTransport/Overview.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_SendOverview {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_SendOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TerminalFastInitFlag.asp?mode=TerminalFastInitFlagCommit&amp;TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_SetFastInitFlag {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_SetFastInitFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TerminalS3Log.asp?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalAnalysisMenu_TerminalEvents {
            get {
                return ResourceManager.GetString("TerminalAnalysisMenu_TerminalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Contract/ContractNew.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_ContractCreate {
            get {
                return ResourceManager.GetString("TerminalMenu_ContractCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Deactivate {
            get {
                return ResourceManager.GetString("TerminalMenu_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalDuplicate.aspx?&apos;].
        /// </summary>
        internal static string TerminalMenu_Duplicate {
            get {
                return ResourceManager.GetString("TerminalMenu_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalView.aspx?PageMode=edit&amp;TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Edit {
            get {
                return ResourceManager.GetString("TerminalMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalForms.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Forms {
            get {
                return ResourceManager.GetString("TerminalMenu_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/InfoText/TerminalInfoTextNew.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_InfotextCreate {
            get {
                return ResourceManager.GetString("TerminalMenu_InfotextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/InfoText/TerminalInfoTextList.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Infotexts {
            get {
                return ResourceManager.GetString("TerminalMenu_Infotexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Contract/PMSCreate.aspx?&apos;].
        /// </summary>
        internal static string TerminalMenu_PmsCreate {
            get {
                return ResourceManager.GetString("TerminalMenu_PmsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalReplace.aspx?TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Replace {
            get {
                return ResourceManager.GetString("TerminalMenu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Contract/ServiceCenterCreate.aspx?&apos;].
        /// </summary>
        internal static string TerminalMenu_ServiceCenterCreate {
            get {
                return ResourceManager.GetString("TerminalMenu_ServiceCenterCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/Terminal/TerminalView.aspx?PageMode=view&amp;TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Terminal {
            get {
                return ResourceManager.GetString("TerminalMenu_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/ticket.asp?WindowName=NewTicket&amp;CUSTOMERID=&apos;].
        /// </summary>
        internal static string TerminalMenu_TicketCreate {
            get {
                return ResourceManager.GetString("TerminalMenu_TicketCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TicketList.asp?ListType=terminal&amp;TERMINALID=&apos;].
        /// </summary>
        internal static string TerminalMenu_Tickets {
            get {
                return ResourceManager.GetString("TerminalMenu_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TicketIntegration/MyPersonalTickets/&apos;].
        /// </summary>
        internal static string TicketMenu_My {
            get {
                return ResourceManager.GetString("TicketMenu_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TicketIntegration/MyGroupTickets/&apos;].
        /// </summary>
        internal static string TicketMenu_MyGroup {
            get {
                return ResourceManager.GetString("TicketMenu_MyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td#leftHandMenu a[href*=&apos;/TicketIntegration/UnAssignedTickets/&apos;].
        /// </summary>
        internal static string TicketMenu_NotAssigned {
            get {
                return ResourceManager.GetString("TicketMenu_NotAssigned", resourceCulture);
            }
        }
    }
}
