//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Tests.SCSClassics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Tests.SCSClassics.Properties.ScsRes", typeof(ScsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcpos.
        /// </summary>
        internal static string mandant_prod {
            get {
                return ResourceManager.GetString("mandant_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcposk.
        /// </summary>
        internal static string mandant_qa_K {
            get {
                return ResourceManager.GetString("mandant_qa_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tkcposl.
        /// </summary>
        internal static string mandant_qa_L {
            get {
                return ResourceManager.GetString("mandant_qa_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mdzhwcweb01/mgmt/.
        /// </summary>
        internal static string UAC_DEV {
            get {
                return ResourceManager.GetString("UAC_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gate.telekurs.ch/scss.
        /// </summary>
        internal static string WES_Production {
            get {
                return ResourceManager.GetString("WES_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateint.telekurs.ch/scsc-qa-k.
        /// </summary>
        internal static string WES_QA_K {
            get {
                return ResourceManager.GetString("WES_QA_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateint.telekurs.ch/scsc-qa-l.
        /// </summary>
        internal static string WES_QA_L {
            get {
                return ResourceManager.GetString("WES_QA_L", resourceCulture);
            }
        }
    }
}
