using System.Collections.Generic;

namespace Six.Scs.Test.Provider
{
    public static class Softwares
    {
        public static IEnumerable<string> Provider281()
        {
            return new[]
            {
                "ARS Thales [74]",
                "Artema Modular Innocard [1060]",
                "Cardpay EP2 [31]",
                "Carus EP2 [41]",
                "cCredit xenta PINPAD [1062]",
                "cCredit xentissimo PINPAD [1070]",
                "cCredit yomani XR PINPAD [1097]",
                "Commtrain EP2 [40]",
                "Datatrans e-Commerce [1098]",
                "davinci AUTONOM [1015]",
                "davinci CASHLOAD [1032]",
                "davinci CHECKOUT [1018]",
                "davinci PINPAD [1014]",
                "davinci PINPAD Contactless [1028]",
                "davinci SAFE [1021]",
                "davinci SAFE AUTONOM [1024]",
                "davinci VENDING [1013]",
                "davinci2 AUTONOM [1053]",
                "davinci2 CHECKOUT AUTONOM [1103]",
                "davinci2 CHECKOUT PINPAD [1102]",
                "davinci2 PINPAD [1054]",
                "davinci2 PINPAD PETROL [1113]",
                "davinci2 SAFE CLP AUTONOM [1100]",
                "davinci2 SAFE CLP PINPAD [1101]",
                "davinci2 TAP [1082]",
                "davinci2 VENDING [1066]",
                "davinci2 VENDING PETROL [1114]",
                "eftgate [1042]",
                "ICP Bia EP2 (Retail) [1072]",
                "ICP Bia EP2 Autonom (Petrol) [1071]",
                "iCT220 EM + iPP220 AUTONOM [1106]",
                "iCT220 GEM + iPP220 AUTONOM [1115]",
                "iCT250 EM COMPACT [1116]",
                "iCT250 GEM COMPACT [1117]",
                "InnoCard EP2 [1052]",
                "iPP320 EM COMPACT [1129]",
                "iPP350 EM COMPACT [1130]",
                "iWL220 BT PORTABLE [1119]",
                "iWL220 GPRS MOBILE [1118]",
                "iWL250 BT PORTABLE [1121]",
                "iWL250 GPRS MOBILE [1120]",
                "Paysys EP2 [42]",
                "SK20 [1105]",
                "smash AUTONOM [19]",
                "smash COMPACT [1011]",
                "smash MOBILE [1016]",
                "smash PINPAD [1012]",
                "Softwareterminal e-Commerce [144]",
                "Verdi Compact [75]",
                "Vibbek [1125]",
                "WN Vx700 Terminal [1089]",
                "WN Vx810 Terminal [1091]",
                "XA Ingenico [73]",
                "xenta AUTONOM [1037]",
                "xenta COMPACT [1035]",
                "xenta PINPAD [1036]",
                "xentissimo [1025]",
                "xentissimo PINPAD [1034]",
                "yomani AUTONOM [1085]",
                "yomani PINPAD [1067]",
                "yomani XR AUTONOM [1093]",
                "yomani XR COMPACT [1094]",
                "yomani XR PETROL [1112]",
                "yomani XR PINPAD [1092]",
                "yomani XR PINPAD PRINTER [1126]",
                "yomani XR SELFCHECKOUT PINPAD [1095]",
                "yomani1 SELFCHECKOUT PINPAD [1088]",
                "yoximo [1104]",
                "yoximo PINPAD [1122]"
            };
        }
    }
}