//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIX.SCS.QA.Selenium.Tests.SCSPlatin.TestObjects.Location {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Location {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Location() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIX.SCS.QA.Selenium.Tests.SCSPlatin.TestObjects.Location.Location", typeof(Location).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AddressAddition.
        /// </summary>
        internal static string Location_AdressAddition {
            get {
                return ResourceManager.GetString("Location_AdressAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _City.
        /// </summary>
        internal static string Location_City {
            get {
                return ResourceManager.GetString("Location_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _LocationName.
        /// </summary>
        internal static string Location_CompanyName {
            get {
                return ResourceManager.GetString("Location_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CountryId.
        /// </summary>
        internal static string Location_Country {
            get {
                return ResourceManager.GetString("Location_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Email.
        /// </summary>
        internal static string Location_Email {
            get {
                return ResourceManager.GetString("Location_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fax.
        /// </summary>
        internal static string Location_Fax {
            get {
                return ResourceManager.GetString("Location_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _LanguageId.
        /// </summary>
        internal static string Location_Language {
            get {
                return ResourceManager.GetString("Location_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mobile.
        /// </summary>
        internal static string Location_Mobile {
            get {
                return ResourceManager.GetString("Location_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PO.
        /// </summary>
        internal static string Location_Po {
            get {
                return ResourceManager.GetString("Location_Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Region.
        /// </summary>
        internal static string Location_Region {
            get {
                return ResourceManager.GetString("Location_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SapNumber.
        /// </summary>
        internal static string Location_SapNumber {
            get {
                return ResourceManager.GetString("Location_SapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Street.
        /// </summary>
        internal static string Location_StreetName {
            get {
                return ResourceManager.GetString("Location_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Telephone.
        /// </summary>
        internal static string Location_Telephone {
            get {
                return ResourceManager.GetString("Location_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Web.
        /// </summary>
        internal static string Location_Web {
            get {
                return ResourceManager.GetString("Location_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ZIP.
        /// </summary>
        internal static string Location_Zip {
            get {
                return ResourceManager.GetString("Location_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #LocationData.
        /// </summary>
        internal static string LocationPrefix {
            get {
                return ResourceManager.GetString("LocationPrefix", resourceCulture);
            }
        }
    }
}
